{
  "Grupo": [
    "Alberto D. Piñones",
    "Alis Foods",
    "CEM",
    "DAQU",
    "Dolmont",
    "DAQU",
    "FEDOZA",
    "Grupo Mega",
    "Grupo RCO",
    "Grupo Titán",
    "Internacional Hinojosa Margain",
    "Jaktur",
    "José Zhul / Carlos Wong",
    "Pizzas de Alta Calidad",
    "Servicios Meta (DINEK)",
    "Otra"
  ],
  "Ciudades": [
    "Apodaca",
    "Araró",
    "Atizapán de Zaragoza",
    "Boca del Río",
    "Cancún",
    "CDMX",
    "Ciénega de Flores",
    "Ciudad Juárez ",
    "Ciudad Victoria",
    "Ecuandureo",
    "Ensenada ",
    "Escobedo",
    "Guadalupe",
    "Guaymas ",
    "Hermosillo",
    "Huizquilucan",
    "Jalostitlán",
    "León",
    "Madero",
    "Matamoros ",
    "Monclova",
    "Monterrey",
    "Naucalpan",
    "Nogales",
    "Nuevo Laredo",
    "Ocotlán",
    "Orizaba",
    "Panindicuaro",
    "Piedras Negras",
    "Puebla",
    "Querétaro",
    "Reynosa",
    "Sabinas, Coahuila",
    "Saltillo",
    "San Luis Potosí ",
    "San Nicolás de los Garza",
    "Tampico",
    "Tepatitlán",
    "Tlalnepantla",
    "Tonalá",
    "Tuxpan",
    "Zapotlanejo"
  ],
  "Sucursales": [
    "Zona Esmeralda",
    "Herradura",
    "Interlomas",
    "Bellavista",
    "Echegaray",
    "Tecamachalco",
    "Zona Azul",
    "Santa Mónica",
    "Valle Dorado / Arboledas",
    "Calzada Acoxpa",
    "Anaxágoras",
    "Azteca",
    "Las Águilas",
    "Ajusco",
    "Zona Rosa ",
    "Copilco",
    "Florida",
    "Félix Cuevas",
    "Insurgentes Tlalpan",
    "Río Bamba",
    "Leones",
    "Miguel Ángel de Quevedo",
    "Miramontes",
    "Moliere ",
    "Nápoles",
    "Polanco",
    "Prado Norte",
    "Sonora ",
    "Roma ",
    "San Jerónimo",
    "Santa Fe",
    "Xola ",
    "Euroten ",
    "Azcapotzalco",
    "Ensenada",
    "Suc. Plaza las Torres",
    "Suc. Centro",
    "Suc. Piedras Negras (Juan Pablo II)",
    "Suc. Saltillo",
    "Suc. Saltillo 2",
    "Suc. Pape (Monclova)",
    "Suc. Sabinas",
    "León A",
    "León B",
    "Cortijo",
    "Jalostitlán",
    "Joya",
    "Ocotlán",
    "Tepatitlán",
    "Ecuandureo B",
    "Panindicuaro",
    "Zinapecuaro",
    "Suc Pablo Livas",
    "Suc. Chapultepec",
    "Suc. Cadereyta",
    "Suc. Aeropuerto",
    "Suc. Apodaca",
    "Suc. Cumbres",
    "Suc. Libramiento",
    "Suc. Concordia",
    "Suc. Universidad",
    "Suc. Rómulo Garza",
    "Suc. Huexotitla",
    "Suc. La Paz",
    "Suc. Cholula",
    "Suc. Angelopolis",
    "Suc. Parque 2000",
    "Suc. Jardines",
    "Suc. Milenium",
    "Plaza del Ángel",
    "López Portillo",
    "Kabah",
    "Suc. Himalaya",
    "Suc. Carranza",
    "Suc. Parador",
    "Sucursal Satélite ",
    "Pitic ",
    "Nogales",
    "Morelos",
    "Guayamas",
    "Suc. Guerrero",
    "Suc. Infonavit",
    "Suc. Colinas",
    "Suc La Fe",
    "Suc. Jarachina",
    "Suc. Lázaro Cárdenas",
    "BLVD Hidalgo",
    "Suc. Plaza Sendero",
    "Suc. Gonzalez",
    "Suc. Plaza Fiesta",
    "Suc. Lomas de Rosales",
    "Suc. Cesar Lopez",
    "Suc. Madero Ampliacion",
    "Suc. Madero Centro",
    "Suc. Cd. Victoria",
    "Suc. Orizaba",
    "Suc. Boca del Río (Torre Ocean)",
    "Suc. Centro"
  ],
  "FormatoImpreso": [
    "Lona",
    "Banner",
    "Vinil",
    "Menú board",
    "Menú carta",
    "Cartelera",
    "Flyer",
    "Espectacular",
    "Otro"
  ],
  "FormatoDigital": [
    "Facebook",
    "Video Facebook",
    "Instagram",
    "Instagram Story",
    "Web - Desktop",
    "Web - Tablet",
    "Web - Mobile",
    "Google Ad",
    "Carrusel Facebook",
    "Otro"
  ],
  "OtrosFormatos": [
    "Spot radio",
    "Mención radio",
    "Prensa",
    "Material RRHH",
    "Otro"
  ]
}
